# Generated by Django 5.2.6 on 2026-01-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialsummary',
            name='dinero_restante',
        ),
    ]
