# Generated by Django 5.2.6 on 2026-01-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion', '0002_remove_financialsummary_dinero_restante'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsummary',
            name='decripcion_gasto',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
